# Run from go-backend: golangci-lint run ./cmd/... ./internal/...
# golangci-lint v2.9+ config
version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019"   # grpc.DialContext deprecation -- migration tracked separately
        - "-ST1000"   # package comments -- not enforced yet
        - "-ST1003"   # naming conventions -- existing code uses JsonRPC prefix
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
    paths:
      - vendor-forks
