# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ipc import ipc_pb2 as ipc_dot_ipc__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ipc/ipc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonIPCStub(object):
    """IPC Service defines the standard gRPC interface between Go Gateway and Python Data/ML Layer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMarketData = channel.stream_unary(
                '/ipc.PythonIPC/StreamMarketData',
                request_serializer=ipc_dot_ipc__pb2.MarketData.SerializeToString,
                response_deserializer=ipc_dot_ipc__pb2.Empty.FromString,
                _registered_method=True)
        self.AnalyzeSoftSignal = channel.unary_unary(
                '/ipc.PythonIPC/AnalyzeSoftSignal',
                request_serializer=ipc_dot_ipc__pb2.SoftSignalRequest.SerializeToString,
                response_deserializer=ipc_dot_ipc__pb2.SoftSignalResponse.FromString,
                _registered_method=True)
        self.PerformInference = channel.unary_unary(
                '/ipc.PythonIPC/PerformInference',
                request_serializer=ipc_dot_ipc__pb2.InferenceRequest.SerializeToString,
                response_deserializer=ipc_dot_ipc__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.ForwardRequest = channel.unary_unary(
                '/ipc.PythonIPC/ForwardRequest',
                request_serializer=ipc_dot_ipc__pb2.ProxyRequest.SerializeToString,
                response_deserializer=ipc_dot_ipc__pb2.ProxyResponse.FromString,
                _registered_method=True)


class PythonIPCServicer(object):
    """IPC Service defines the standard gRPC interface between Go Gateway and Python Data/ML Layer
    """

    def StreamMarketData(self, request_iterator, context):
        """StreamMarketData sends high-frequency tick data from Go to Python
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSoftSignal(self, request, context):
        """AnalyzeSoftSignal requests Python to process unstructured text (e.g. news)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformInference(self, request, context):
        """PerformInference requests Python to run a specific ML model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardRequest(self, request, context):
        """ForwardRequest forwards an HTTP-style request to the Python service (method + path + body).
        Enables gRPC for all Python endpoints. Python forwards to its internal HTTP handlers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonIPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMarketData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamMarketData,
                    request_deserializer=ipc_dot_ipc__pb2.MarketData.FromString,
                    response_serializer=ipc_dot_ipc__pb2.Empty.SerializeToString,
            ),
            'AnalyzeSoftSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSoftSignal,
                    request_deserializer=ipc_dot_ipc__pb2.SoftSignalRequest.FromString,
                    response_serializer=ipc_dot_ipc__pb2.SoftSignalResponse.SerializeToString,
            ),
            'PerformInference': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformInference,
                    request_deserializer=ipc_dot_ipc__pb2.InferenceRequest.FromString,
                    response_serializer=ipc_dot_ipc__pb2.InferenceResponse.SerializeToString,
            ),
            'ForwardRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardRequest,
                    request_deserializer=ipc_dot_ipc__pb2.ProxyRequest.FromString,
                    response_serializer=ipc_dot_ipc__pb2.ProxyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipc.PythonIPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ipc.PythonIPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonIPC(object):
    """IPC Service defines the standard gRPC interface between Go Gateway and Python Data/ML Layer
    """

    @staticmethod
    def StreamMarketData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ipc.PythonIPC/StreamMarketData',
            ipc_dot_ipc__pb2.MarketData.SerializeToString,
            ipc_dot_ipc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSoftSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipc.PythonIPC/AnalyzeSoftSignal',
            ipc_dot_ipc__pb2.SoftSignalRequest.SerializeToString,
            ipc_dot_ipc__pb2.SoftSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipc.PythonIPC/PerformInference',
            ipc_dot_ipc__pb2.InferenceRequest.SerializeToString,
            ipc_dot_ipc__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipc.PythonIPC/ForwardRequest',
            ipc_dot_ipc__pb2.ProxyRequest.SerializeToString,
            ipc_dot_ipc__pb2.ProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
