// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: ipc.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PythonIPC_StreamMarketData_FullMethodName  = "/ipc.PythonIPC/StreamMarketData"
	PythonIPC_AnalyzeSoftSignal_FullMethodName = "/ipc.PythonIPC/AnalyzeSoftSignal"
	PythonIPC_PerformInference_FullMethodName  = "/ipc.PythonIPC/PerformInference"
	PythonIPC_ForwardRequest_FullMethodName    = "/ipc.PythonIPC/ForwardRequest"
)

// PythonIPCClient is the client API for PythonIPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IPC Service defines the standard gRPC interface between Go Gateway and Python Data/ML Layer
type PythonIPCClient interface {
	// StreamMarketData sends high-frequency tick data from Go to Python
	StreamMarketData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MarketData, Empty], error)
	// AnalyzeSoftSignal requests Python to process unstructured text (e.g. news)
	AnalyzeSoftSignal(ctx context.Context, in *SoftSignalRequest, opts ...grpc.CallOption) (*SoftSignalResponse, error)
	// PerformInference requests Python to run a specific ML model
	PerformInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	// ForwardRequest forwards an HTTP-style request to the Python service (method + path + body).
	// Enables gRPC for all Python endpoints. Python forwards to its internal HTTP handlers.
	ForwardRequest(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
}

type pythonIPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPythonIPCClient(cc grpc.ClientConnInterface) PythonIPCClient {
	return &pythonIPCClient{cc}
}

func (c *pythonIPCClient) StreamMarketData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MarketData, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PythonIPC_ServiceDesc.Streams[0], PythonIPC_StreamMarketData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MarketData, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PythonIPC_StreamMarketDataClient = grpc.ClientStreamingClient[MarketData, Empty]

func (c *pythonIPCClient) AnalyzeSoftSignal(ctx context.Context, in *SoftSignalRequest, opts ...grpc.CallOption) (*SoftSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftSignalResponse)
	err := c.cc.Invoke(ctx, PythonIPC_AnalyzeSoftSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonIPCClient) PerformInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, PythonIPC_PerformInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonIPCClient) ForwardRequest(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, PythonIPC_ForwardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PythonIPCServer is the server API for PythonIPC service.
// All implementations must embed UnimplementedPythonIPCServer
// for forward compatibility.
//
// IPC Service defines the standard gRPC interface between Go Gateway and Python Data/ML Layer
type PythonIPCServer interface {
	// StreamMarketData sends high-frequency tick data from Go to Python
	StreamMarketData(grpc.ClientStreamingServer[MarketData, Empty]) error
	// AnalyzeSoftSignal requests Python to process unstructured text (e.g. news)
	AnalyzeSoftSignal(context.Context, *SoftSignalRequest) (*SoftSignalResponse, error)
	// PerformInference requests Python to run a specific ML model
	PerformInference(context.Context, *InferenceRequest) (*InferenceResponse, error)
	// ForwardRequest forwards an HTTP-style request to the Python service (method + path + body).
	// Enables gRPC for all Python endpoints. Python forwards to its internal HTTP handlers.
	ForwardRequest(context.Context, *ProxyRequest) (*ProxyResponse, error)
	mustEmbedUnimplementedPythonIPCServer()
}

// UnimplementedPythonIPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPythonIPCServer struct{}

func (UnimplementedPythonIPCServer) StreamMarketData(grpc.ClientStreamingServer[MarketData, Empty]) error {
	return status.Error(codes.Unimplemented, "method StreamMarketData not implemented")
}
func (UnimplementedPythonIPCServer) AnalyzeSoftSignal(context.Context, *SoftSignalRequest) (*SoftSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSoftSignal not implemented")
}
func (UnimplementedPythonIPCServer) PerformInference(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PerformInference not implemented")
}
func (UnimplementedPythonIPCServer) ForwardRequest(context.Context, *ProxyRequest) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedPythonIPCServer) mustEmbedUnimplementedPythonIPCServer() {}
func (UnimplementedPythonIPCServer) testEmbeddedByValue()                   {}

// UnsafePythonIPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PythonIPCServer will
// result in compilation errors.
type UnsafePythonIPCServer interface {
	mustEmbedUnimplementedPythonIPCServer()
}

func RegisterPythonIPCServer(s grpc.ServiceRegistrar, srv PythonIPCServer) {
	// If the following call panics, it indicates UnimplementedPythonIPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PythonIPC_ServiceDesc, srv)
}

func _PythonIPC_StreamMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PythonIPCServer).StreamMarketData(&grpc.GenericServerStream[MarketData, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PythonIPC_StreamMarketDataServer = grpc.ClientStreamingServer[MarketData, Empty]

func _PythonIPC_AnalyzeSoftSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonIPCServer).AnalyzeSoftSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonIPC_AnalyzeSoftSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonIPCServer).AnalyzeSoftSignal(ctx, req.(*SoftSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonIPC_PerformInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonIPCServer).PerformInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonIPC_PerformInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonIPCServer).PerformInference(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonIPC_ForwardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonIPCServer).ForwardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonIPC_ForwardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonIPCServer).ForwardRequest(ctx, req.(*ProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PythonIPC_ServiceDesc is the grpc.ServiceDesc for PythonIPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PythonIPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipc.PythonIPC",
	HandlerType: (*PythonIPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSoftSignal",
			Handler:    _PythonIPC_AnalyzeSoftSignal_Handler,
		},
		{
			MethodName: "PerformInference",
			Handler:    _PythonIPC_PerformInference_Handler,
		},
		{
			MethodName: "ForwardRequest",
			Handler:    _PythonIPC_ForwardRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketData",
			Handler:       _PythonIPC_StreamMarketData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ipc.proto",
}
